from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

button_1 = KeyboardButton("✅ Tasdiqlash")
button_2 = KeyboardButton("✅ Подтверждение")
button_3 = KeyboardButton("✅ Confirm")
button_4 = KeyboardButton("❌ Bekor qilish")
button_5 = KeyboardButton("❌ Отказать")
button_6 = KeyboardButton("❌ Ignore")
button_7 = KeyboardButton("🏠 Bosh menyu")
button_8 = KeyboardButton("🏠 Главное меню")
button_9 = KeyboardButton("🏠 Main menu")
button_10 = KeyboardButton("⬅ Ortga")
button_11 = KeyboardButton("⬅ Назад")
button_12 = KeyboardButton("⬅ Back")
con_or_del_uz = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(button_1, button_4).row(button_7)
con_or_del_ru = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(button_2, button_5).row(button_8)
con_or_del_en = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(button_3, button_6).row(button_9)
confirm_or_delete_order_uz = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(button_1, button_4)
confirm_or_delete_order_ru = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(button_2, button_5)
confirm_or_delete_order_en = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(button_3, button_6)
con_del_back_uz = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(button_1, button_4).row(button_10)
con_del_back_ru = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(button_2, button_5).row(button_11)
con_del_back_en = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True).row(button_3, button_6).row(button_12)