from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

button_1 = KeyboardButton(text="🇺🇿 O'zbek")
button_2 = KeyboardButton(text="🇷🇺 Русский")
button_3 = KeyboardButton(text="🇬🇧 English")
button_4 = KeyboardButton(text="🏛 Bosh menyu")
button_5 = KeyboardButton(text="🏛 Главное меню")
button_6 = KeyboardButton(text="🏛 Main menu")
button_7 = KeyboardButton(text="🌏 Tilni o'zgartirish")
button_8 = KeyboardButton(text="🌏 Изменить язык")
button_9 = KeyboardButton(text="🌏 Change language")
button_10 = KeyboardButton(text="⬅ Ortga")
button_11 = KeyboardButton(text="⬅ Назад")
button_12 = KeyboardButton(text="⬅ Back")
markup = ReplyKeyboardMarkup(resize_keyboard=True).row(button_1, button_2, button_3)
markup_uz_lang = ReplyKeyboardMarkup(resize_keyboard=True).row(button_1, button_2, button_3).row(button_10)
markup_ru_lang = ReplyKeyboardMarkup(resize_keyboard=True).row(button_1, button_2, button_3).row(button_11)
markup_en_lang = ReplyKeyboardMarkup(resize_keyboard=True).row(button_1, button_2, button_3).row(button_12)
mark_up_change_language_uz = ReplyKeyboardMarkup(resize_keyboard=True).row(button_7).row(button_10)
mark_up_change_language_ru = ReplyKeyboardMarkup(resize_keyboard=True).row(button_8).row(button_11)
mark_up_change_language_en = ReplyKeyboardMarkup(resize_keyboard=True).row(button_9).row(button_12)
back_uz = ReplyKeyboardMarkup(resize_keyboard=True).row(button_10)
back_ru = ReplyKeyboardMarkup(resize_keyboard=True).row(button_11)
back_en = ReplyKeyboardMarkup(resize_keyboard=True).row(button_12)